#!/bin/bash
#
# Copyright 2015 HLRS, University of Stuttgart
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Root epilogue for VM.
# Intended for cluster admins, not users,
# like the scripts in /var/spool/torque/mom_priv/
#


#============================================================================#
#                                                                            #
#                          GLOBAL CONFIGURATION                              #
#                                                                            #
#============================================================================#

# source the global profile, for getting DEBUG and TRACE flags if set
source /etc/profile.d/99-mikelangelo-hpc_stack.sh;

#
#
#
source $SCRIPT_BASE_DIR/common/root-config.sh $@;
source $SCRIPT_BASE_DIR/common/root-functions.sh;


#============================================================================#
#                                                                            #
#                          SCRIPT CONFIGURATION                              #
#                                                                            #
#============================================================================#


#
#LOG_FILE=$HOME/.pbs_vm_jobs/logs/epilogue-$JOBID-$LOCALHOST.log;
LOG_FILE=/var/log/pbs_root_epilogue.log;



#============================================================================#
#                                                                            #
#                               FUNCTIONS                                    #
#                                                                            #
#============================================================================#



#============================================================================#
#                                                                            #
#                                 MAIN                                       #
#                                                                            #
#============================================================================#

logDebugMsg "Running VM Epilogue as '$(id)', file: '$(basename ${BASH_SOURCE[0]})'";
logInfoMsg "Root VM epilogue script started.";

copyOutputStreams;

logInfoMsg "Root VM epilogue finished."

# print the consumed time in debug mode
runTimeStats;

# exit the job
exit 0;
